# Generated by Django 4.2.7 on 2023-11-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("domain_name", models.CharField(max_length=255)),
                ("protocol", models.CharField(max_length=5)),
                ("title", models.CharField(max_length=255)),
                ("image", models.JSONField()),
                ("stylesheets", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
