# Generated by Django 4.2.7 on 2023-11-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("part1", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="url",
            old_name="url",
            new_name="url_string",
        ),
    ]
