# Generated by Django 4.2.7 on 2023-11-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("part1", "0002_rename_url_url_url_string"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="image",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
