# Generated by Django 4.2.7 on 2023-11-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("part1", "0003_alter_url_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="protocol",
            field=models.CharField(
                choices=[("H", "Http"), ("HS", "Https")], max_length=5
            ),
        ),
    ]
