# Generated by Django 4.2.7 on 2023-11-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("part1", "0004_alter_url_protocol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="protocol",
            field=models.CharField(
                choices=[("http", "Http"), ("https", "Https")], max_length=5
            ),
        ),
    ]
