# Generated by Django 4.2.7 on 2023-11-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("part1", "0005_alter_url_protocol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="protocol",
            field=models.CharField(
                choices=[("H", "http"), ("HS", "https")], max_length=5
            ),
        ),
    ]
