# Generated by Django 4.2.7 on 2023-11-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("part1", "0006_alter_url_protocol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="url",
            name="image",
        ),
        migrations.AddField(
            model_name="url",
            name="image",
            field=models.ManyToManyField(blank=True, to="part1.url"),
        ),
    ]
