# Generated by Django 4.2.7 on 2023-11-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("part1", "0007_remove_url_image_url_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="url",
            name="image",
        ),
        migrations.AddField(
            model_name="url",
            name="image",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
