# Generated by Django 4.2.7 on 2023-11-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("part1", "0008_remove_url_image_url_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="image",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
